"""initial migration

Revision ID: 23b742b3d9d2
Revises: 
Create Date: 2026-09-13 12:01:48.649545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b742b3d9d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "predictions",

        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),

        sa.Column(
            "input_text",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "prediction",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "confidence",
            sa.Numeric(5, 4),
            nullable=True,
        ),

        sa.Column(
            "model_name",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),

        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="predictions_confidence_range",
        ),

        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predictions")
